### ISSUE TITLE
Fails partway through the unpacking.

### ISSUE THREAD

**Issue by Uradamus** [panzi/psypkg#1]
I was attempting to use this on the latest Steam version of the game for Linux. I created a tmp dir in the game's install dir where I saved the script and intended to unpack to and used the following command.

./psypkg.py unpack ../PsychonautsData2.pkg

It unpacked a good chunk of files but then stopped prematurely with the following error.

[Errno 13] Permission denied: '/lipsync'

On subsequent attempts, I receive the same error and nothing further seems to get unpacked. I'm running Manjaro Linux (64-bit with Mate desktop) and tried out the script with both Python 2 and 3 (2.7.14 & 3.6.3). Both versions give the same error.

**Comment by panzi** [comment]
Hm, I know that I have bugs in the code extracting the file names. I'm surprised that I've not mentioned that in the Readme. So somehow it wants to extract files to an absolute directory (even more bugged than I thought). I added code to fix that at least. Try it again now, but keep in mind that the filenames aren't completely correct (e.g. sometimes there's a missing letter at the start).

**Comment by Uradamus** [comment]
Cool, just tried out the latest version and it seems to have done its thing without any noticeable fuss. Thanks for the quick response! Now I'm onto the next step of figuring out what to do with the files I've unpacked, heh.
